name: Use Secret Example

on: [push]

jobs:
  example:
    runs-on: ubuntu-latest

    env:
      MY_API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show message
        run: echo "Secret is loaded (but not printed)."
